export const WEB_TARGET = process.env.WEB_TARGET || ""
export const WEB_DOMAIN = process.env.WEB_DOMAIN || ""
export const OBS_WEB_SOCKET_URL = process.env.OBS_WEB_SOCKET_URL || ""
export const USER_NAME = process.env.USER_NAME || ""
export const USER_PASS = process.env.USER_PASS || ""